### ISSUE TITLE
Non-matching names

### ISSUE THREAD

**Issue by christophermclement** [saiemgilani/cfbfastR-py#10]
When you pull cfb_rosters you can't link those players back to there teams in some cases because the school ID isn't used, just the name, and the names sometimes don't match what's in the teams data, even if you join both the cfbd and espn names

The non-matching teams are:

{'Louisiana Monroe', 'St Francis (PA)', 'Sam Houston State', 'Southeastern Louisiana', 'Connecticut', 'UT San Antonio', 'Prairie View', 'Southern Mississippi', 'Presbyterian College'}

**Comment by saiemgilani** [comment]
file this in sportsdataverse-py's issues: [https://github.com/saiemgilani/sportsdataverse-py/issues](https://github.com/saiemgilani/sportsdataverse-py/issues)

This project will be archived soon
